name: CI
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: sudo apt-get install python3-venv python3-sphinx

      - name: Build Site
        run: cd site && ./build_site.sh prod